# Generated by Django 3.2.25 on 2024-11-06 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='updated_at',
        ),
    ]
