# Generated by Django 3.2.25 on 2024-11-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_remove_workoutlog_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
