# Generated by Django 3.2.25 on 2024-11-07 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout', '0003_auto_20241106_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('number_of_sets', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('number_of_reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rest_between_sets_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_in_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['user', 'name'], name='workout_exe_user_id_390345_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_exercise_name'),
        ),
    ]
