# Generated by Django 3.2.25 on 2024-11-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_auto_20241107_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='exercise',
            field=models.ManyToManyField(blank=True, null=True, to='workout.Exercise'),
        ),
    ]
