# Generated by Django 3.2.25 on 2024-11-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_workoutlog_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='exercise',
            field=models.ManyToManyField(blank=True, to='workout.Exercise'),
        ),
    ]
