# Generated by Django 3.2.25 on 2024-11-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_alter_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
