# Generated by Django 3.2.25 on 2024-11-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_alter_exercise_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutlog',
            old_name='exercise',
            new_name='exercises',
        ),
    ]
