# Generated by Django 3.2.25 on 2024-11-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0009_rename_exercise_workoutlog_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='exercises',
            field=models.ManyToManyField(to='workout.Exercise'),
        ),
    ]
