# Generated by Django 3.2.25 on 2024-11-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0011_alter_workoutlog_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='workout.Exercise'),
        ),
    ]
