# Generated by Django 3.2.25 on 2024-11-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('number_of_sets', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('number_of_reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rest_between_sets_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_in_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
