# Generated by Django 3.2.25 on 2024-11-11 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_remove_workoutlog_exercises'),
        ('exercise', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='duration_in_minutes',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='number_of_reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='number_of_sets',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='rest_between_sets_seconds',
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_sets', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('number_of_reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rest_between_sets_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_in_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
                ('workout_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workoutlog')),
            ],
        ),
    ]
