# Generated by Django 3.2.25 on 2024-11-13 02:40

from django.db import migrations, models
import exercise.validators


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_alter_exerciselog_duration_in_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=254, validators=[exercise.validators.validate_exercise_name]),
        ),
    ]
