# Generated by Django 3.2.25 on 2024-11-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_alter_exercise_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exercise',
            name='exercise_ex_user_id_991fde_idx',
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['name'], name='exercise_ex_name_27aa8f_idx'),
        ),
    ]
