# Generated by Django 3.2.25 on 2024-11-13 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0011_exerciselog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='created_AT',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
