# Generated by Django 3.2.25 on 2024-11-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0012_exercise_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='created_AT',
        ),
    ]
