# Generated by Django 3.2.25 on 2024-11-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0014_exerciselog_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciselog',
            old_name='weight',
            new_name='weight_in_kg',
        ),
    ]
