# Generated by Django 3.2.25 on 2024-11-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20241106_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bmi',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
